### ISSUE TITLE
Requirements are not clear

### ISSUE THREAD

**Issue by jjgray** [Graylab/deepH3-distances-orientations#2]
1. need to add Python version (3.6)

1. Best practice is to not specify exact versions, but rather give version > # to allow flexibility

https://github.com/Graylab/deepH3-distances-orientations/blob/master/requirements.txt

**Comment by cguerramain** [comment]
I replaced the == with >= in the training-clean-up branch, see [https://github.com/Graylab/deepH3-distances-orientations/commit/a66ba5ca0f991075a1e7f66f21b246abfada6f78](url).
As for the python3.6+ requirement, the specification in the README should be enough.
